version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  db-test:
    image: postgres
    ports:
      - "45433:5432"
    expose:
      - "45433"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - default